### ISSUE TITLE
Column metadata not retrieved (IBM Data Engine)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-connector-hivemetastore#115]
* Create a new IBM Data Engine instance (standard)
* Create a sample 'customer' table (use as-provided)
* Configure HMS connector to point to instance & start

Result:
 * Table 'customer' is found & an appropriate RelationalTable with the correct name 'customer' and unique name 'hms1spark.default.schema-type.customers' is sent out in the Kafka message - as expected
 * Single column 'col' is found. This is sent as a RelationalColumn with the name name 'col' and unique name hms1spark.default.schema-type.customers.col - wrong
 
 This is incorrect, the customer table contains many columns, beginning (but there's more)
 ```
customerID string,
companyName string,
contactName string,
contactTitle string,
```

In addition - to avoid any client filtering of tables with content hosted on inaccessible object storage, I repeated the test with
* Saving a 'select *' output to personal block storage (csv)
* Creating a new table 'nigelcust' referring to the above csv

The same results were seen, but with the table 'nigelcust'

**Comment by planetf1** [comment]
<img width="1604" alt="Screenshot 2023-02-15 at 19 08 43" src="https://user-images.githubusercontent.com/7292002/219128482-c1837fad-188d-4c05-a98e-2c128297240e.png">

**Comment by planetf1** [comment]
Tested with some standalone code - no shading, no egeria libraries, thrift/hadoop libs at same version as original - same, only 'col' returned from hive metastore.

**Comment by planetf1** [comment]
In some standalone code, the fieldSchema was retrieved as:
```
[main] INFO hivemetastore.App - Table(tableName:customers, dbName:default, owner:spark, createTime:1676483141, lastAccessTime:0, retention:0, sd:StorageDescriptor(cols:[FieldSchema(name:col, type:array<string>, comment:from deserializer)], location:file:/tmp/customers-__PLACEHOLDER__, inputFormat:org.apache.hadoop.mapred.SequenceFileInputFormat, outputFormat:org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat, compressed:false, numBuckets:-1, serdeInfo:SerDeInfo(name:null, serializationLib:org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, parameters:{mode=FAILFAST, path=cos://sql-eu-de.samples/customers.csv, header=true, serialization.format=1}), bucketCols:[], sortCols:[], parameters:{}, skewedInfo:SkewedInfo(skewedColNames:[], skewedColValues:[], skewedColValueLocationMaps:{}), storedAsSubDirectories:false), partitionKeys:[], parameters:{bucketing_version=2, spark.sql.sources.schema={"type":"struct","fields":[{"name":"customerID","type":"string","nullable":true,"metadata":{}},{"name":"companyName","type":"string","nullable":true,"metadata":{}},{"name":"contactName","type":"string","nullable":true,"metadata":{}},{"name":"contactTitle","type":"string","nullable":true,"metadata":{}},{"name":"address","type":"string","nullable":true,"metadata":{"comment":"Street and house number"}},{"name":"city","type":"string","nullable":true,"metadata":{}},{"name":"region","type":"string","nullable":true,"metadata":{"comment":"NULL for countries where not applicable"}},{"name":"postalCode","type":"string","nullable":true,"metadata":{}},{"name":"country","type":"string","nullable":true,"metadata":{}},{"name":"phone","type":"string","nullable":true,"metadata":{}},{"name":"fax","type":"string","nullable":true,"metadata":{}}]}, EXTERNAL=TRUE, spark.sql.sources.provider=CSV}, viewOriginalText:null, viewExpandedText:null, tableType:EXTERNAL_TABLE, temporary:false, rewriteEnabled:false, catName:spark, ownerType:USER)
```

**Comment by planetf1** [comment]
From this we see
 - the NAME of the FIELDSCHEMA is 'col'
 - spark.sql.sources.schema contains the schema info
 - an example column is represented as `{"name":"customerID","type":   "string","nullable":true,"metadata":{}`

**Comment by planetf1** [comment]
Not familar with the api, however I would have expected the tables to also appear FieldSchema. Unsure if this is a backend issue. Could be a derialization issue (and hence build/class related) given the comment 'from deserializer')

**Comment by planetf1** [comment]
Browsing through sample code it seems as if:
* Schema is often stored in spark.sql.sources.schema, perhaps this is old, but it's also typically found in the storage descriptor. [Example hinted at - though this is REST](https://github.com/nsi-dwaine/CDM/blob/34bd34f9260140a8f8aa02bd87c23033f3daad4c/objectModel/TestData/Storage/TestSymsAdapter/ExpectedOutput/expectedUpdatedTableResponse.json#L108)
* Very large schemas may be split across multiple parts [SPARK-6024](https://github.com/apache/spark/pull/4795) - check spark.sql.sources.schema.numParts
* Some references to the schema only containing 'col'
 - https://github.com/delta-io/delta/pull/1579
 - https://github.com/apache/spark/pull/13073
 - [Comment referencing population of the schema / col](https://github.com/tedyu/spark/blob/13e8c2840969a17d5ba113686501abd3c23e3c23/sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveExternalCatalog.scala#L1372)

**Comment by planetf1** [comment]
It may be that our algorithm for retrieving metadata needs to be something like

if (hms table serializer defined)
 get configured serializer
 load seralizer
 get fields using serializer (this will get from the spark.* properties)
else
 get fiends from storage descriptor ie table.getSd().getCols -- as we do now

**Comment by planetf1** [comment]
Most examples appear to show the storage descriptor populated.

Trying to confirm expected behaviour for this service. We may need to add specific code to read spark specific metadata stored in properties.

**Comment by davidradl** [comment]
During my testing with Data engine, I see some of the columns correctly set up and reaching Egeria and some come through as a single "col". I will check with the IBM Data Engine team to understand more.

**Comment by davidradl** [comment]
It appears that view metadata does come through but EXTERNAL_TABLES do not have the storage descriptor cols populated. For an example of Spark data source parquet table see. [https://stackoverflow.com/questions/42726069/how-to-saveastable-to-hive-so-that-the-hive-table-is-managed-table](https://stackoverflow.com/questions/42726069/how-to-saveastable-to-hive-so-that-the-hive-table-is-managed-table). It seems that the usage of `  spark.sql.sources.provider  parquet             
    spark.sql.sources.schema.numParts   1                   
    spark.sql.sources.schema.part.0 {\"type\":\"struct\",\"fields\":` to hold column information is standard practice for Spark data sources.

**Comment by planetf1** [comment]
A few more references 
 - https://issues.apache.org/jira/browse/SPARK-21841 relating to scenarios where a table is updated
 
 which suggests some more subtlety with regards to when the hive-compatible definition under the storage descriptor is updated
 
But then also some code at https://github.com/apache/kyuubi/pull/1476/files which seems to have logic to pull the table definitions either from the sd, or from spark specific schema if needed, looking as if this may depend on the storage provider? WOuld be good to understand the general case here beyond just spark (though that is crucial)

**Comment by planetf1** [comment]
we should also consider precedence or consistency checks ie what happens if schema is found in both locations

**Comment by davidradl** [comment]
@planetf1 from what I can see from the cases the storage descriptor content is an array of strings, this content is then processed for a particular data source and more detailed columns are written to the table parameters. I think handling this on a per table type basis should be ok initially and assessing each new case as we need to support it.  
 
I guess generally there are 3 situations: 
- vanilla Hive on HMS and any customizations that can occur (e.g. custom Serializer/Deserializer). This will not have the spark table parameters
- the Spark HMS set up. This will have the spark table parameters - but the storage descriptor is populated for views.
- any other non Spark HMS scenarios.

**Comment by davidradl** [comment]
@planetf1 I agree we should document what use cases with HMS we support.
