### ISSUE TITLE
Create a polling thread in the repository proxy to issue queries

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-hivemetastore#12]
- [x] Copy over the file repository proxy content
- [x] change the package names
- [x] amend the gradle build script to bring in the patched hive dependancy
- [x] change the code to use the HMS client instead of the file access.
- [x] Very basic round trip for an asset to work (this might not be the right asset) 
- [x] Agree open types to use
- [x] Test against  vanilla HMS client
- [x] guid <-> qualified name round trip mapper for entities and relationships for schemas
- [x] implement schema content 
- [x] implement events
- [x] confirm appropriate column types - i.e. strings to use for integers dates strings etc.  
- [x] Decide what to do with derived columns  - exclude views for now
- [ ] check that audit log content is appropriate and comes out
- [x] Check that connection endpoint can be specified reasonably for a Cloud environment (where asset endpoint urls can be more consistent - will test on IBM Cloud to Data Engine to prove this) 
- [ ] Investigate whether it is possible to expose a connection endpoint for a Vanilla Hive    
- [ ] update readme
- [x] Test with Rex against the repository proxy in local mode
- [x] Test with Rex against another metadata server in the cohort that has the entities due to events
- [x] issue event from the event mapper including new schema content 
- [x] run CTS against connector.
- [ ] document 
- [ ] check no TODOs are left
- [ ] Update real docs
- [ ] Consider testing automation. 

Create a polling thread in the event mapper to issue queries via the repository connector. This issue will be used to document the design and the thread. The polling thread should be switched on using a configuration option. The polling thread is not the normal way a repository proxy server would function. The normal way a repository proxy server would work would be that federated queries, would result in queries to the connector which would bring the 3rd party content into the cohort. This option of a polling thread issuing queries that result in refresh events is being added for the case where federated queries are not being issued in the cohort.

**Comment by mandy-chessell** [comment]
Some comments on the proposal.  Probably just clarification on terminology...

* The Repository Proxy is a type of OMAG server - not a connector.
* There are two connectors that support a third party repository in the Repository Proxy:
     * OMRSRepositoryConnector - wraps the repository APIs.  **It is not able to send events to the cohort.**
     * OMRSEventMapper - provides event notification to the rest of the cohort based on the activity in the third party repository (HMS in this case).  Ideally this would be from events but it can be from queries to HMS since the event mapper is able to call its OMRS repository connector (which calls HMS).
* The events from the event mapper typically describe changes to the third party repository.  However refresh events allow the current state of an element to be broadcast to the cohort.
* There are two types of refresh events:
    * **Refresh request** - asking the home repository to send the latest version of the element to the cohort - this is typically used by other members of the cohort to update their reference copy of the element.  They need the GUID to send the refresh request event.  They do not know the GUID until the element has been shared at least once with the cohort.  This typically occurs through a federated query.  However if there are no cohort members capable of issuing federated queries in the cohort then any metadata in HMS that was added before it joined the cohort is dark to the other members until it is changed, resulting in events from its event mapper.
    * **Refresh response** - event containing the current state of the element.  The refresh response can be sent without a refresh request.  This can be used by the event mapper to broadcast information about the metadata in HMS that was present before HMS joined the cohort.

The event mapper is the connector that is responsible for creating refresh response events and this is where the polling thread needs to be controlled from - **not the repository connector**.  Also note:

* The event mapper is mandatory if any type of events are to be supported by the Repository Proxy.  If no event mapper is supplied, the Repository Proxy disables outbound event management.

* The thread's operation can be controlled from the configuration properties in the connection configured for the event mapper connector.

**Comment by davidradl** [comment]
@mandy-chessell that is great. Thank you very much for the clarifications.

**Comment by davidradl** [comment]
@mandy-chessell The event mapper would use the mapper if it were processing  HMS events. I assume in the polling case it does not need to map, and that the event mapper issues calls to the repository connector that in turn calls HMS, the event mapper is returned OMRS entities and relationships, which it then puts on the cohort topic. Is this the way you would see this working?

**Comment by davidradl** [comment]
@mandy-chessell I recall there was an option to batch OMRS events. Could this be used here? I am thinking something like 
- query HMS databases, send a single event containing the granular refresh response OMRS events,  
- query HMS tables, send a single event for each table containing its columns and relationships as granular refresh response OMRS events.

**Comment by mandy-chessell** [comment]
I think so - you would have to test it.  But you also need to be careful of very wide tables - ie thousands of columns - that can occur in data science projects.

**Comment by mandy-chessell** [comment]
Also note that the event mapper connector is passed an event processor object (between `initialize()` method and `start()` method).

```
/**
     * Set up the repository event processor for this connector to use.  The connector should pass
     * each typeDef or instance metadata change reported by its metadata repository's metadata on to the
     * repository event processor.
     *
     * @param repositoryEventProcessor listener responsible for distributing notifications of local
     *                                changes to metadata types and instances to the rest of the
     *                                open metadata repository cohort.
     */
    void setRepositoryEventProcessor(OMRSRepositoryEventProcessor repositoryEventProcessor);
```

This is the object that the event mapper passes the OMRS Events to.  The event processor manages the delivery of the event.

**Comment by davidradl** [comment]
Great - thanks @mandy-chessell . I assume the 'batching' is done using the `InstanceGraph  instanceBatch` within OMRSInstanceEvent.

**Comment by mandy-chessell** [comment]
It may be.  The event mapper should not work with the low level event structures because it is hard to populate it correctly.  

If you want to know for sure, trace the appropriate call from the OMRSRepositoryEventProcessor, such as `processInstanceBatchEvent()` down to where it converts the parameters into the event.

**Comment by davidradl** [comment]
@mandy-chessell I was wondering

Option 1) if it is possible to accumulate all the information we need for the event in the repository connector? With the scope of the calls to HMS to put together a payload representing a Hive tables would be determined in the repository connector. In this way the appropriate entities and relationships for a HMS table could be accumulated and 'given' to the eventmapper, minimizing the number of calls to HMS.

Option 2) The alternative is that the eventmapper issues queries based on on omrs types and then gets the relationships for each entity, then gets the entity details as required. The scope of the calls to HMS to put together a payload representing a Hive tables would be determined in the event mapper. For example to piece together entities like the below picture would mean multiple calls to the repository connector resulting in possible the same HMS call each time bring out different parts :
<img width="804" alt="image" src="https://user-images.githubusercontent.com/39792797/164968049-3e23feeb-ece3-4b04-98df-d47b1ccedd0c.png">
 
I assume option 2 is the way the current design for Egeria is - is there a way to implement option 1? Currently I cant think of a way to do this. Also if we implemented option 2 a query for entities with a the connector type could be honoured ,

I am thinking option 2 is the way we need to go, but would like feedback on whether there is a way to do option 1.    @cmgrote  @mandy-chessell  @planetf1 @lpalashevski @wbittles any thoughts?

**Comment by mandy-chessell** [comment]
The event mapper and repository connector are matched in terms of granularity.
With the exception of the batch event, each event is equivalent to a a single instance (entity, relationship, classificationExtension).  Therefore when the event mapper issues a find request to the repository connector, it is going to get a list of instances back - ie content for many events.
It would then be possible to put all of the instances returned in the list into a batch event.  

The occasion when you may consider caching HMS content into the repository connector is if the API for HMS is very much more course-grained than OMRS and you are expecting related elements to be received in a short space of time.  For example, if a table and all of its columns is returned in one call to HMS then these results could be cached for a short peroid of time.  Then you could use a nested OMRS repository connector to do this.  However this design decision is independent from the operation of the event mapper.  

I would suggest getting the event mapper mechanism working and then look at whether the OMRS repository connector can be optimized with caching.  It has to consider that many HMS repositories are very large and any caching needs to be handled with care.

**Comment by wbittles** [comment]
Option 3, it's a new type of connector that needs to be discussed in the main egeria repo

**Comment by mandy-chessell** [comment]
Agreed - but I don't think a new type of connector is necessary since the requirements being discussed are well within the capabilities of the current architecture.  The discussion is about ensuring the different functional pieces are put in the right components.

**Comment by davidradl** [comment]
@wbittles @mandy-chessell thanks for your feedback. I will start prototyping some of the plumbing that is required for option 2. I will leave the repository connector implementation (i.e. the Hive specifics) with you. I will need to make some assumptions on the types to use.

Billy I am not convinced we need an option 3; if you want to pursue a new connector type, please put together a proposal and present the details to the community (or include all the details in an issue where a discussion can be held) - please include why the existing connector types are not sufficient. I agree with Mandy that we should get option 2 functionally working then look to optimise if there are performance issues. I can throw any prototyping work away, if the community agrees we should pursue a new option 3 connector type.

**Comment by wbittles** [comment]
The requirements being discussed in this issue don't match what is being discussed with the users.
For instance the solution that has been promised to the customers doesn't have a metadata collection

**Comment by mandy-chessell** [comment]
So HMS is empty?

**Comment by mandy-chessell** [comment]
If you mean the OMRSMetadataCollection interface being discussed above then it is a mandatory part of the OMRSRepositoryConnector interface.   It won't build without it.  

All OMRSRepositoryConnectors include an implementation of this OMRSMetadataCollection since this is the interface that is mapped to the third party repository ie HMS in this case.   If an OMRSRepositoryConnector has been promised then it will have an implementation of OMRSMetadataCollection.

**Comment by wbittles** [comment]
@mandy-chessell we are integrating with a main central repository which is the centre of the system and answers all queries from it's own repository.
The component that has been promised allows the system to bypass the existing eventing mechanism and replace it with a polling system and runtime that this central system controls. There is no need to deploy listeners etc.

The only time this component actually interops with the egeria cohort is when a change has been detected, all the relevant type mappings have been carried out and batched into a single kafka event that is written directly into the cohort kafka topic. It purely a one way sync process for another cataloging system

**Comment by mandy-chessell** [comment]
@wbittles  For the consumer you are thinking about, the  "main central repository" sounds like it has a metadata collection otherwise there would be no metadata to publish events about.  Its operation also sounds normal for a third party metadata repository.  They all typically have their own APIs and answer metadata queries directly as well as integrate with open metadata.  For example, this is true fo Apache Atlas, IGC and SAS Viya.

In general an HMS does have a metadata collection.  Storing metadata is after all what HMS is good at.   So querying/receiving events about metadata from an HMS is likely to be valuable to most consumers of this function.

The top of this issue is suggesting a need to send refresh response events.  These events do not refer to changes in metadata.  Refresh response events are used for members in the cohort to receive events about metadata from HMS that:
* was in HMS before it joined the cohort
* last changed before the other member joined the cohort

This is necessary for the consumer that @davidradl is working with because none of the cohort members are able to issue federated queries to retrieve this metadata directly.   They do not want to wait until a metadata element is updated in HMS before they get an event for it.

Having said that, the design described above only supports one-way syncing through events in the way that you state.  This was my understanding of the requirement.   To have events from other members of the cohort syncing into HMS (ie a 2-way or inbound sync), the HMS repository connector would need to implement the methods for managing reference copies.  As such we would be having a different discussion.

If your particular consumer does not want the refresh events and only wants to know about elements that are changing then they control that on the receiving side either through configuration or the security connector.  This is standard behaviour of the cohort which is peer-to-peer in nature.  Each member choses what to share and what to receive.  They are independent of one another.

**Comment by wbittles** [comment]
@mandy-chessell your absolutely spot on about the central repo having it's own metadata collection, which consists of Egeria types. But the component we are discussing doesn't support any incoming requests it will be functionally equivalent of just installing an event mapper on it's own. No GUID'S, verifTypes, get Entity....

I'm fact I was wrong earlier the component doesn't even reconcile for changes, again that is done centrally by the consumer. During every poll, this component coverts the entire contents of the HMS into egeria types and batches them into per table kafka events.

**Comment by davidradl** [comment]
@wbittles a repository proxy server will need to be aware of Egeria types, and generate guids (the types, qualified names and guids are in the OMRS events); it will also have its own metadata collection id. I can see that the initial work is only to send out events - as this is the priority use cases we are working on currently. The repository proxy server takes archives (the same way as a metadata server), so has the open types and any other types that have been supplied in archives; I only realised this recently - apologies if I have misled you in this respect.

@mandy-chessell , the order we are looking at implementing this is 
1- refresh events from HMS repository connector based on the polling as we have been discussing
2- processing inbound events from another member of the cohort - with a different metadata collection id. This should create reference copies.  
3- support the create, delete and update events - if the polling it not granular enough.   

The scope of this issue is first item at this stage.

To be fully functional, this component will also need to be able to handle incoming query requests- as this is what other users of this repository proxy server will expect. It also allows us to be tested using the CTS. I see this work is probably further down the line (after we have implemented the 3 items) , but "option 2 - polling from the event mapper that calls the repository connector" will allow processing of incoming queries with minimal rewrite.

**Comment by wbittles** [comment]
@davidradl We are not discussing a repository connector server, that's why I suggest it needs to be a new type of Egeria component. Of course this new component will need to do any necessary type mapping I called that out above. 
I don't understand "takes archives" sounds like another new feature ? 
Can you explain why we need GUID's in this situation ?

**Comment by davidradl** [comment]
@wbittles I think using the repository connector makes sense to use here. Here is my thinking and thoughts on your questions.

 By 'takes archives' I mean using the archive manager. This is not new feature but the normal way that repository proxy and metadata servers get access to the open types. So it can validate types and include the correct typedef content in an entity. An EntityDetail includes a property call type which is an InstanceType. 
 
As to why we need guids, the refresh response event will contain a list of OMRS entities and relationships. Each entity and relationship needs to be well formed; this means that the provenance needs to be correctly set, its type is set (this includes the TypeDef guid) and also each entity and relationship each needs a unique guid that the repository proxy will need to generate. When a 3rd party repository proxy receives the entities and relationships in the event, it will expect the guids to be unique and is likely to use the guids to correlate with existing content in its store. 

I think we talked about how we would do this guid generation a while back. This is the sort of thing we talked of I think:
 - finding a way of uniquely identifying each database / table / schema element etc with a qualified name. This is likely going to be a long string. Something like <3rd party instance>-<database name>-<table name>-<column name>   
 - Then have helper methods for entities that could take the qualified name and generate a guid, and take a guid and generate a qualified name. 
 - These helper methods would be used so we could correlate 3rd party content with the Egeria entities and vice versa. 
 - I assume the guid of a relationship would be generated from the qualified names of the entities at each end and would have similar helper methods  

This would allow the event mapper to issue queries to the repository connector and also getEntityByGuid if it needed more details as required.    

I think you are suggesting that a new connector type would issue the 3rd party query calls directly and then produce an event. The Egeria architecture has all 3rd party queries being issued via a repository connector. I like this separation of concerns: 
- one connector for issuing the queries to the 3rd party metadata store (with associated configuration including the 3rd party endpoints) 
- the other is the event mapper connector, handling events including the Kafka Cohort topic configuration. 
It is a normal pattern for event mappers to call repository connectors to get extra information required to fill out events; this would mean we use existing tested framework and patterns to implement this.

**Comment by wbittles** [comment]
@davidradl  This isn't a repository connector and it does not match what will has been promised or what will be delivered to the customer, but I've extremely happy to diverege and leave Egeria to do it's own thing thing.

**Comment by davidradl** [comment]
We had a community call today , the following architecture emerged. 3 points came out that were new:
- we should consider a short lived in memory cache to hold the recently retrieved entities and relationships. Invalidate the cache every minute or so. In this way we can minimise the calls to HMS.    
- It is a common pattern that the event mapper is called with minimal identifying information , and issues a call to the repository connector to get a complete well formed OMRS entities. So option 2 is using the common pattern. 
- @lpalashevski indicated that the [data stage connector](https://github.com/odpi/egeria-connector-ibm-information-server/tree/master/datastage-adapter/src/main/java/org/odpi/egeria/connectors/ibm/datastage/dataengineconnector) uses this pattern including the caching.
-  
<img width="429" alt="image" src="https://user-images.githubusercontent.com/39792797/165283028-9ac7e9ba-7eca-46dc-8659-190ba296647f.png">

@mandy-chessell @lpalashevski could you check that I represented this correctly.

**Comment by davidradl** [comment]
@mandy-chessell I have an owner on a table that come from Hive, is there a way to store this associated with the table (not the database asset)?
