### ISSUE TITLE
The Readme looks incomplete

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-hivemetastore#4]
I suggest:
1) we do not refer to Egeria as ODPi Egeria any more - now we have moved to LF AI and Data
2) Typo in `Hivw Metastore connector`
3) The link behind `Hivw Metastore connector` is broken
4) Sentence `To learn more about configuring Repository Proxy servers` is not complete,

**Comment by wbittles** [comment]
well spotted , I have actually got a full README here , but all the links pointed to the old Web site and the commands and captured output hadn't been updated in a few releases.
It wil be complete eventually, just not highest priority at the minute.
