### ISSUE TITLE
Provide suitable hive metastore environment for dev & test

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-connector-hivemetastore#5]
Provide a suitable environment for developing and testing the hive metastore.

Ideally this should include docs & relevant artifacts to support running a hive metastore environment locally for development, and as part of a ci/cd process for functional testing

This is part of the work required for #2
#6 should define the required levels to support

**Comment by planetf1** [comment]
Hive requires hadoop plus a database such as postgres for the metadata repository

I took a look at existing helm charts / containers that might provide hive metastore capabilities:

Current version of hive is 3.1.2


https://hub.kubeapps.com/charts/gradiant/hive-metastore
 - chart repo on longer listed
 - version 2.3.6
 - docker image years ago

https://docs.starburst.io/latest/k8s/hms-configuration.html
 - commercial

https://medium.com/quintoandar-tech-blog/old-but-gold-implementing-a-hive-metastore-infrastructure-225a8056fea8
 - medium
 - https://github.com/amommendes/helm-hive-metastore
 - version 3.0.0

MR3
 - proprietary
 - not open license - https://mr3docs.datamonad.com/docs/license/

Helm chart & docker just for HDFS from GCHQ -> https://github.com/gchq/gaffer-docker

2020 deprecated helm chart for hadoop - https://github.com/zonca/zonca-blog/blob/master/_posts/2021-10-12-kubernetes-hadoop.md

Dated chart for hadoop/spark - https://github.com/apache-spark-on-k8s/kubernetes-HDFS

IBM docker hive - https://github.com/IBM/docker-hive (2.10.1, hive 2.3.9)

**Comment by planetf1** [comment]
None of the above are openly licensed, and particularly usable and up to date with the latest release of Hive (3.1.2)

Rather than have a very scalable, flexibly hive metastore 'install', it may be more appropriate to build a custom container or chart that just lays down a basic hadoop install, plus hive. This should be good enough for initial development/testing. 

It would not scale to performance testing etc, but this could be contributed by potential users of the hive metastore.

**Comment by wbittles** [comment]
Thanks for the notes , and unfortunately your suggestion is not adequate.

**Comment by wbittles** [comment]
It's not obvious why MR3 has been ruled out , it looks like our only option trying to move this forward. 

MR3

    proprietary
    not open license - https://mr3docs.datamonad.com/docs/license/

**Comment by planetf1** [comment]
Dev configuration
--
* A simple test configuration is useful to develop the connector and run simple tests. What exceptions were seen? Could it have been configuration issues? Or were you driving under high load? A simple config could be run locally, or within existing github executors fairly easily (probably by building a docker container).I would strongly suggest we persue/review any inhibitors to this

* A multinode setup IS complex - such as the comms between the nodes, certainly doable with k8s, but it's a not-trivial piece of work. It could be simplified for a well-defined environment, but to do generically would be a lot more. this is something where we would want to reuse something already developed

Whilst 'meaty' in terms of CPU would be a concern with many processes/components/load, that's not so much a problem. We could exceed github limits -- and need to use external resource. What's more crucial is reuse, portability - whether a paid for service, vm, container, so something that is scriptable, automatable, reusable - or that is maintained elsewhere.

On MR3, in terms of ease of use of deployment, I agree it looks interesting. The one caveat is licensing. the text states available under Apache 2.0, and the hive fork is, but the docs refer to a DataMonad license - with the k8s repository not showing any license, which any org using the software (including development) would need to be ok with.  This immediately makes it less portable, but I agree with you it's worth persuing given the state of hive/hadoop. 

Given the complexity I would suggest both of:
 * review the use of Hive metadata single-node to see if we can use this to support dev+many test needs
 * persuing MR2 for a larger system test (and possibly to replace above if it looks good)

**Comment by planetf1** [comment]
Using the project at https://github.com/IBM/docker-hive I was able to
 * connect to the Hive metastore running in a container at port 9083 & use the IMetaStore interface (from some basic python)
  * Build a custom container -- though the very latest commit is a big refactor and causes a breakage - one commit back is ok
  
  This provides a *basic* hive metastore environment. hiveserver2 (port 10000, jdbc interface) is not enabled - at least by default
  
  This could be an option for simple dev/test, if viable I would engage with the committers to check status/expectations
  
  We would need sample metadata as per the solution requirements, and would still want to test again a full environment
