### ISSUE TITLE
Document business problem & outline solution

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-connector-hivemetastore#6]
Document an outline of the problem that this solution is solving.

Document the outline solution, including expected infrastructure that will be supported - for examples versions of the hive metastore, what metadata is supported, type of connector

**Comment by planetf1** [comment]
This should include the type mappings from Hive metastore to Egeria

**Comment by wbittles** [comment]
Here is the initial type mapping that was agreed on the developers call.
![Hive2Egeria-Page-4](https://user-images.githubusercontent.com/47160261/152219973-9cabb035-b127-469e-8344-785fa4589109.svg)

**Comment by davidradl** [comment]
@wbittles This looks like the Egeria types you are looking to populate. The mapping would involve documenting the Hive artifacts and properties and mapping each artifact and property to the Egeria types. One way to do this would be to create json files like the Atlas connector [https://github.com/odpi/egeria-connector-hadoop-ecosystem/tree/master/apache-atlas-adapter/src/main/resources](https://github.com/odpi/egeria-connector-hadoop-ecosystem/tree/master/apache-atlas-adapter/src/main/resources  )

**Comment by davidradl** [comment]
@wbittles I am a bit confused HiveTable and HiveDatabase are not currently Egeria types. Are you working with draft versions of these types to prove they are correct before we add them to Egeria?

**Comment by davidradl** [comment]
The business problem, is that we would like to bring hive metastore (HMS) metadata around tables and columns into the Egeria ecosystem.

The proposed solution is to use the same pattern and the sample polling file OMRS connector, excpet to change out the file specifics to make HMS calls.


HMS will be called using a client based on  org.apache.hive:hive-standalone-metastore. We are looking to connect to a HMS running at version 3.1.2. The open source versions bring in vulnerabilities in log4j. We are looking to use the client referred to [https://cloud.ibm.com/docs/sql-query?topic=sql-query-hive_metastore#hive_compatible_client](https://cloud.ibm.com/docs/sql-query?topic=sql-query-hive_metastore#hive_compatible_client) - which is patched.

We are looking to use the non-specialised Egeria types including:
Entity types
            Asset 
            Referenceable
            OpenMetadataRoot
            Connection,
            TypeEmbeddedAttribute
            ConnectorType,
            Endpoint,
Relationship types
           ConnectionEndpoint,
           ConnectionConnectorType,
          ConnectionToAsset, 
           RelationalDBSchemaType,
            RelationalTable,
            RelationalColumn,
           NestedSchemaAttribute,
           AttributeForSchema,
           SchemaAttribute

The Classification that embeds the type is likely going to be used.

**Comment by mandy-chessell** [comment]
I would recommend that if no specialized types are defined, the Hive database is represented by `Database` rather than `Asset`.

**Comment by davidradl** [comment]
@mandy-chessell good spot - I meant to include Database (I am using it!) I will edit the list

**Comment by wbittles** [comment]
@mandy-chessell @davidradl  While the below is specific to Hive I believe it also applies to MySQL and MariaDB

Hive databases are slightly different in architecture than most typical RDBMS, one of the peculiarities is that a "database" and a "schema" are functionally equivalent. The role usually performed by a typical database tends to be performed by a "catalogue". 

This can actually work with the current types but only if the API returns the same list of names for each query ShowDatabases and ShowSchemas . Egeria  ends up with a structure like 

databaseName.databaseName.tableName
schemaName.schemaName.tableName

ideally Egeria would want to represent a typical Hive structure which would look more like. 

datbaseName.tableName structure.

**Comment by davidradl** [comment]
> @mandy-chessell @davidradl While the below is specific to Hive I believe it also applies to MySQL and MariaDB
> 
> Hive databases are slightly different in architecture than most typical RDBMS, one of the peculiarities is that a "database" and a "schema" are functionally equivalent. The role usually performed by a typical database tends to be performed by a "catalogue".
> 
> This can actually work with the current types but only if the API returns the same list of names for each query ShowDatabases and ShowSchemas . Egeria ends up with a structure like
> 
> databaseName.databaseName.tableName schemaName.schemaName.tableName
> 
> ideally Egeria would want to represent a typical Hive structure which would look more like.
> 
> datbaseName.tableName structure.

@wbittles I have updated the readme with the mappings from the HMS content to the open types, that the connector is using. I believe this will be sufficient for the current requirements. We could consider more Hive specific types - as new requirements come in. 

When I look at the HMS client, I do not see a showSchema - I see a getSchema API that returns a list of SchemaFields. So there does not appear to be a schema object as such.
When I issue getTable I am returned a Table object that contains the list of SchemaFields as well as the table name. 

I also notice there are APIs like getSchemaAllVersions - that need a schema name as input, I am not sure how to get the schemaName to drive this API. I am looking into whether we can store schema versions in Egeria.

**Comment by davidradl** [comment]
closing as this has been coded and the problem and solution space agreed. If there are further concerns they should be raised in new issues.  I am not going to add anything to do with schema versions at this stage.
