### ISSUE TITLE
Update gradle build to publish/sign artifact, create javadocs, use correct groupid

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-connector-hivemetastore#8]
We need to be able to publish the build artifact to maven central

In build.gradle
  - [ ] The group id should be 'org.odpi.egeria'
  - [ ] Bring up the version of egeria to 3.5 (last release- but only as of this week!)
  - [ ] Add in the content around signing and publishing as seen in https://github.com/odpi/egeria-database-connectors/blob/main/build.gradle - this file also addresses some CI specific settings, enables java linting, javadocs, source
  - [ ] Add gradle wrapper

**Comment by wbittles** [comment]
@mandy-chessell seemed to be requiring a certain level of CTS compliance for the first drop of the connector and as the needs of the project will be realized ahead of the CTS , I think this can wait.
It also means that well be using a CI with a manual delivery mechanism, i.e the connector must pass CTS    before it could be released.

**Comment by planetf1** [comment]
* Changed first section to a 'todo' list (to avoid creating many individual issues)
* Noted we need a gradle wrapper for build consistency 

This is getting a basic compile to support ci - so issue should be addressed early on - we need a reproducible process to build the connector as part of egeria. This is one of the first required steps.

This is also a basis for introducing a basic ci pipeline in #7 

Agreed, connector should pass CTS. But initial testing- including from potential users - can be on a tech preview basis. Caveats, limitations can be documented. CTS process should be put in place, that will build on top of the above
